<?php
//sub	 bgs		focu	bg	filt	thumb	 slip	li

	$tpl = array(
	
		array(
			'tpltypeid'=>1,
			'tplview'=>'cate1.png',
			'tpltypename'=>'101_index',
			'tpldesinfo'=>'',
			'attr'=>'thumb focu bgs',
			'sort'=>1,
		),	
		
		array(
			'tpltypeid'=>2,
			'tplview'=>'cate2.png',
			'tpltypename'=>'102_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'focu bgs lis white',
			'sort'=>2,
		),
		
		array(
			'tpltypeid'=>3,
			'tplview'=>'cate3.png',
			'tpltypename'=>'103_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'focu bgs lis white',
			'sort'=>3,
		),
				
		array(
			'tpltypeid'=>4,
			'tplview'=>'cate4.png',
			'tpltypename'=>'104_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'thumb focu bgs lis white',
			'sort'=>4,
		),
						
		array(
			'tpltypeid'=>5,
			'tplview'=>'cate9.png',
			'tpltypename'=>'105_index',
			'tpldesinfo'=>'文字标签式模版，顶部幻灯片尺寸为640*320或近似等比例图片。',
			'attr'=>'focu bgs',
			'sort'=>5,
		),
								
		array(
			'tpltypeid'=>6,
			'tplview'=>'cate106.png',
			'tpltypename'=>'106_index_ydkds',
			'tpldesinfo'=>'',
			'attr'=>'focu thumb bgs white',
			'sort'=>6,
		),
										
		array(
			'tpltypeid'=>7,
			'tplview'=>'cate107.png',
			'tpltypename'=>'107_index_2d8si',
			'tpldesinfo'=>'',
			'attr'=>'focu thumb bgs black',
			'sort'=>7,
		),

		array(
			'tpltypeid'=>8,
			'tplview'=>'cate108.png',
			'tpltypename'=>'108_index_giw93x',
			'tpldesinfo'=>'',
			'attr'=>'filt focu bgs purple',
			'sort'=>8,
		),
		
		array(
			'tpltypeid'=>9,
			'tplview'=>'cate109.png',
			'tpltypename'=>'109_index_0fdis',
			'tpldesinfo'=>'',
			'attr'=>'focu bgs color',
			'sort'=>9,
		),
				
		array(
			'tpltypeid'=>10,
			'tplview'=>'cate110.png',
			'tpltypename'=>'110_index_2skz7',
			'tpldesinfo'=>'',
			'attr'=>'bgs focu thumb black blue',
			'sort'=>10,
		),
						
		array(
			'tpltypeid'=>11,
			'tplview'=>'cate111.png',
			'tpltypename'=>'111_index_78yus',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片。',
			'attr'=>'bgs focu thumb white',
			'sort'=>11,
		),

		array(
			'tpltypeid'=>12,
			'tplview'=>'cate112.png',
			'tpltypename'=>'112_index_kj7y5',
			'tpldesinfo'=>'',
			'attr'=>'bg bgs filt black',
			'sort'=>12,
		),
		
		array(
			'tpltypeid'=>13,
			'tplview'=>'cate113.png',
			'tpltypename'=>'113_index_jks6z',
			'tpldesinfo'=>'',
			'attr'=>'bg bgs filt black',
			'sort'=>13,
		),
		
		array(
			'tpltypeid'=>14,
			'tplview'=>'cate114.png',
			'tpltypename'=>'114_index_mnsz6',
			'tpldesinfo'=>'',
			'attr'=>'thumb filt bg bgs black bg',
			'sort'=>14,
		),
		
		array(
			'tpltypeid'=>15,
			'tplview'=>'cate115.png',
			'tpltypename'=>'115_index_ms76x',
			'tpldesinfo'=>'',
			'attr'=>'bgs bg filt black',
			'sort'=>15,
		),
		
		array(
			'tpltypeid'=>16,
			'tplview'=>'cate116.png',
			'tpltypename'=>'116_index_ms76x',
			'tpldesinfo'=>'图片式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，文字为分类名称及分类描述，名称建议4个字符，描述限制10个字符以内；图片为分类封面，建议尺寸为宽165*高100或近似等比例图片',
			'attr'=>'thumb focu bgs',
			'sort'=>16,
		),
		
		array(
			'tpltypeid'=>17,
			'tplview'=>'cate117.png',
			'tpltypename'=>'117_index_usn3x',
			'tpldesinfo'=>'图标式模板',
			'attr'=>'thumb filt bg bgs red2',
			'sort'=>17,
		),
		
		array(
			'tpltypeid'=>18,
			'tplview'=>'cate118.png',
			'tpltypename'=>'118_index_jge3',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片。',
			'attr'=>'thumb focu bgs green2',
			'sort'=>18,
		),
		
		array(
			'tpltypeid'=>19,
			'tplview'=>'cate119.png',
			'tpltypename'=>'119_index_jsg2',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片。',
			'attr'=>'focu thumb bgs white',
			'sort'=>19,
		),
		
		array(
			'tpltypeid'=>20,
			'tplview'=>'cate120.png',
			'tpltypename'=>'120_index_pfs9',
			'tpldesinfo'=>'支持二级分类，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，幻灯下4个图标为分类管理的前4个分类，图标下第一块内容为第五个分类的分类封面、分类名称及子分类名称，建议尺寸300*300或1:1图片，下面依次类推。',
			'attr'=>'focu thumb bgs sub pink color',
			'sort'=>20,
		),
		
		array(
			'tpltypeid'=>21,
			'tplview'=>'cate121.png',
			'tpltypename'=>'121_index_eor5w',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，分类前8个为图标及文字展示，后面分类为图片展示，建议尺寸为宽150*高90或等比例图片。',
			'attr'=>'focu bgs thumb sub pink color',
			'sort'=>21,
		),

		array(
			'tpltypeid'=>22,
			'tplview'=>'cate122.png',
			'tpltypename'=>'122_index_pgj9d',
			'tpldesinfo'=>'图标式模板，按分类顺序依次展现，有图片显示的分类，图片尺寸建议为宽150*85高或的等比例图片。',
			'attr'=>'bgs thumb color blue purple',
			'sort'=>22,
		),
		
		array(
			'tpltypeid'=>23,
			'tplview'=>'cate123.png',
			'tpltypename'=>'123_index_jge4s',
			'tpldesinfo'=>'汽车行业专属模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，幻灯下4个图标为分类管理的前4个分类，后面分类依次展示，图片建议尺寸为宽302*高233或等比例图片，logo图标为官网logo，需等比尺寸的png格式图片。',
			'attr'=>'focu bgs white',
			'sort'=>23,
		),
		
		array(
			'tpltypeid'=>24,
			'tplview'=>'cate124.png',
			'tpltypename'=>'124_index_ghe5s',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示8个二级分类。',
			'attr'=>'focu bgs thumb white sub',
			'sort'=>24,
		),
		
		array(
			'tpltypeid'=>25,
			'tplview'=>'cate125.png',
			'tpltypename'=>'125_index_gjnh4',
			'tpldesinfo'=>'左右双栏模版，顶部幻灯片尺寸为640*320或近似等比例图片，如使用正方形图片会使得页面不美观；分类图片建议使用300*200或近似等比例图片，使用宽度小于高度的(如200*300)尺寸图片将使页面惨不忍睹。',
			'attr'=>'bgs focu thumb',
			'sort'=>25,
		),
		
		array(
			'tpltypeid'=>26,
			'tplview'=>'cate126.png',
			'tpltypename'=>'126_index_gjj0f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'focu thumb bgs color',
			'sort'=>26,
		),
		
		array(
			'tpltypeid'=>27,
			'tplview'=>'cate127.png',
			'tpltypename'=>'127_index_jpr4g',
			'tpldesinfo'=>'',
			'attr'=>'focu bgs thumb black',
			'sort'=>27,
		),
		
		array(
			'tpltypeid'=>28,
			'tplview'=>'cate128.png',
			'tpltypename'=>'128_index_pgj3f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'focu bgs thumb blue',
			'sort'=>28,
		),
		
		array(
			'tpltypeid'=>29,
			'tplview'=>'cate129.png',
			'tpltypename'=>'129_index_fds3f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'focu bgs thumb red2 color',
			'sort'=>29,
		),
		
		array(
			'tpltypeid'=>30,
			'tplview'=>'cate130.png',
			'tpltypename'=>'130_index_ves7g',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'focu bgs thumb red2 bg',
			'sort'=>30,
		),

		array(
			'tpltypeid'=>31,
			'tplview'=>'cate131.png',
			'tpltypename'=>'131_index_win6a',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示8个二级分类。',
			'attr'=>'focu bgs thumb red2',
			'sort'=>31,
		),
		
		array(
			'tpltypeid'=>32,
			'tplview'=>'cate132.png',
			'tpltypename'=>'132_index_wio1a',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示6个二级分类。',
			'attr'=>'focu bgs thumb',
			'sort'=>32,
		),
		
		array(
			'tpltypeid'=>33,
			'tplview'=>'cate133.png',
			'tpltypename'=>'133_index_wis2a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，小图标为正方形300x300px。',
			'attr'=>'sub focu bgs thumb white',
			'sort'=>33,
		),
		
		array(
			'tpltypeid'=>34,
			'tplview'=>'cate134.png',
			'tpltypename'=>'134_index_viw3a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，小图标为正方形300x300px。',
			'attr'=>'sub focu bgs thumb white',
			'sort'=>34,
		),
		
		array(
			'tpltypeid'=>35,
			'tplview'=>'cate135.png',
			'tpltypename'=>'135_index_you4a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，前4个一级分类可以突出显示，小图标',
			'attr'=>'focu bgs thumb sub white',
			'sort'=>35,
		),		
		array(
			'tpltypeid'=>36,
			'tplview'=>'cate136.png',
			'tpltypename'=>'136_index_esfsd344',
			'tpldesinfo'=>'',
			'attr'=>'thumb bg bgs filt',
			'sort'=>36,
		),
		array(
			'tpltypeid'=>37,
			'tplview'=>'list1.png',
			'tpltypename'=>'yl_list',
			'tpldesinfo'=>'',
			'attr'=>'lis',
			'sort'=>37,
		),
		array(
			'tpltypeid'=>38,
			'tplview'=>'list4.png',
			'tpltypename'=>'ktv_list',
			'tpldesinfo'=>'',
			'attr'=>'lis white',
			'sort'=>38,
		),
		array(
			'tpltypeid'=>39,
			'tplview'=>'cate139.png',
			'tpltypename'=>'139_index_ktv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'focu thumb filt',
			'sort'=>39,
		),
		array(
			'tpltypeid'=>40,
			'tplview'=>'cate140.png',
			'tpltypename'=>'140_index_qesf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'focu thumb bgs blue',
			'sort'=>40,
		),
		array(
			'tpltypeid'=>41,
			'tplview'=>'cate141.png',
			'tpltypename'=>'141_index_654d red2',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'focu thumb bgs pink',
			'sort'=>41,
		),
		array(
			'tpltypeid'=>42,
			'tplview'=>'cate142.png',
			'tpltypename'=>'142_index_6uid',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs filt bg thumb bg',
			'sort'=>42,
		),
		array(
			'tpltypeid'=>43,
			'tplview'=>'cate143.png',
			'tpltypename'=>'143_index_53sd',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs filt bg thumb bg',
			'sort'=>43,
		),
		array(
			'tpltypeid'=>44,
			'tplview'=>'cate144.png',
			'tpltypename'=>'144_index_bfst',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs bg thumb bg blue',
			'sort'=>44,
		),
		array(
			'tpltypeid'=>45,
			'tplview'=>'cate145.png',
			'tpltypename'=>'145_index_vbws',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu blue',
			'sort'=>45,
		),
		array(
			'tpltypeid'=>46,
			'tplview'=>'cate146.png',
			'tpltypename'=>'146_index_58sv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>46,
		),
		array(
			'tpltypeid'=>47,
			'tplview'=>'cate147.png',
			'tpltypename'=>'147_index_verm',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>47,
		),
		array(
			'tpltypeid'=>48,
			'tplview'=>'cate148.png',
			'tpltypename'=>'148_index_bleu',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>48,
		),
		array(
			'tpltypeid'=>49,
			'tplview'=>'cate149.png',
			'tpltypename'=>'149_index_28ad',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>49,
		),
		array(
			'tpltypeid'=>50,
			'tplview'=>'cate150.png',
			'tpltypename'=>'150_index_28sv red2',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color orange',
			'sort'=>50,
		),
		array(
			'tpltypeid'=>51,
			'tplview'=>'cate151.png',
			'tpltypename'=>'151_index_ve4y',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color',
			'sort'=>51,
		),
		array(
			'tpltypeid'=>52,
			'tplview'=>'cate152.png',
			'tpltypename'=>'152_index_v82x',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color',
			'sort'=>52,
		),
		array(
			'tpltypeid'=>53,
			'tplview'=>'cate153.png',
			'tpltypename'=>'153_index_58sdf',
			'tpldesinfo'=>'诺基亚X风格，披着wp外衣的android，不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2 purple',
			'sort'=>53,
		),
		array(
			'tpltypeid'=>54,
			'tplview'=>'cate154.png',
			'tpltypename'=>'154_index_f78d1',
			'tpldesinfo'=>'诺基亚X风格2，不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2 purple',
			'sort'=>54,
		),
		array(
			'tpltypeid'=>55,
			'tplview'=>'cate155.png',
			'tpltypename'=>'155_index_xym7',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color orange',
			'sort'=>55,
		),
		array(
			'tpltypeid'=>56,
			'tplview'=>'cate156.png',
			'tpltypename'=>'156_index_64ay',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu purple color',
			'sort'=>56,
		),
		array(
			'tpltypeid'=>57,
			'tplview'=>'cate157.png',
			'tpltypename'=>'157_index_dgeh7',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>57,
		),
		array(
			'tpltypeid'=>58,
			'tplview'=>'cate158.png',
			'tpltypename'=>'158_index_ffy4',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color blue',
			'sort'=>58,
		),
		array(
			'tpltypeid'=>59,
			'tplview'=>'cate159.png',
			'tpltypename'=>'159_index_fgft',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu purple color',
			'sort'=>59,
		),
		array(
			'tpltypeid'=>60,
			'tplview'=>'cate160.png',
			'tpltypename'=>'160_index_674f',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color orange',
			'sort'=>60,
		),
		array(
			'tpltypeid'=>61,
			'tplview'=>'cate161.png',
			'tpltypename'=>'161_index_df3t',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color',
			'sort'=>61,
		),
		array(
			'tpltypeid'=>62,
			'tplview'=>'cate162.png',
			'tpltypename'=>'162_index_xffe',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu white',
			'sort'=>62,
		),
		array(
			'tpltypeid'=>63,
			'tplview'=>'cate163.png',
			'tpltypename'=>'163_index_cve3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu white',
			'sort'=>63,
		),
		array(
			'tpltypeid'=>64,
			'tplview'=>'cate164.png',
			'tpltypename'=>'164_index_5366',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu filt lis green2 orange',
			'sort'=>64,
		),
		array(
			'tpltypeid'=>65,
			'tplview'=>'cate165.png',
			'tpltypename'=>'165_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color',
			'sort'=>65,
		),
		array(
			'tpltypeid'=>66,
			'tplview'=>'cate166.png',
			'tpltypename'=>'166_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color',
			'sort'=>66,
		),
		array(
			'tpltypeid'=>67,
			'tplview'=>'cate167.png',
			'tpltypename'=>'167_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color blue',
			'sort'=>67,
		),
		array(
			'tpltypeid'=>68,
			'tplview'=>'cate168.png',
			'tpltypename'=>'168_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color',
			'sort'=>68,
		),
		array(
			'tpltypeid'=>69,
			'tplview'=>'cate169.png',
			'tpltypename'=>'169_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color',
			'sort'=>69,
		),
		array(
			'tpltypeid'=>70,
			'tplview'=>'cate170.png',
			'tpltypename'=>'170_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>70,
		),
		array(
			'tpltypeid'=>71,
			'tplview'=>'cate171.png',
			'tpltypename'=>'171_index_stbn',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>71,
		),
		array(
			'tpltypeid'=>72,
			'tplview'=>'cate172.png',
			'tpltypename'=>'172_index_44g3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color',
			'sort'=>72,
		),
		array(
			'tpltypeid'=>73,
			'tplview'=>'cate173.png',
			'tpltypename'=>'173_index_6dff',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color purple',
			'sort'=>73,
		),
		array(
			'tpltypeid'=>74,
			'tplview'=>'cate174.png',
			'tpltypename'=>'174_index_gh46',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color purple',
			'sort'=>74,
		),
		array(
			'tpltypeid'=>75,
			'tplview'=>'cate175.png',
			'tpltypename'=>'175_index_6deh',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color purple',
			'sort'=>75,
		),
		array(
			'tpltypeid'=>76,
			'tplview'=>'cate176.png',
			'tpltypename'=>'176_index_sda3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu brown',
			'sort'=>76,
		),
		array(
			'tpltypeid'=>77,
			'tplview'=>'cate177.png',
			'tpltypename'=>'177_index_gh5f',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu brown',
			'sort'=>77,
		),
		array(
			'tpltypeid'=>78,
			'tplview'=>'cate178.png',
			'tpltypename'=>'178_index_shfr',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'bgs focu lis white',
			'sort'=>78,
		),
		array(
			'tpltypeid'=>79,
			'tplview'=>'cate179.png',
			'tpltypename'=>'179_index_4g4f',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'bgs focu lis white',
			'sort'=>79,
		),
		array(
			'tpltypeid'=>80,
			'tplview'=>'cate180.png',
			'tpltypename'=>'180_index_zfg4',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'bgs focu lis black',
			'sort'=>80,
		),
		array(
			'tpltypeid'=>81,
			'tplview'=>'cate181.png',
			'tpltypename'=>'181_index_dfg3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>81,
		),
		array(
			'tpltypeid'=>82,
			'tplview'=>'cate182.png',
			'tpltypename'=>'182_index_sd3v',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu orange brown',
			'sort'=>82,
		),
		array(
			'tpltypeid'=>83,
			'tplview'=>'cate183.png',
			'tpltypename'=>'183_index_zdfe',
			'tpldesinfo'=>'图片高度100，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu orange brown',
			'sort'=>83,
		),
		array(
			'tpltypeid'=>84,
			'tplview'=>'cate184.png',
			'tpltypename'=>'184_index_sdf3',
			'tpldesinfo'=>'图片高度100，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu brown',
			'sort'=>84,
		),
		array(
			'tpltypeid'=>85,
			'tplview'=>'cate185.png',
			'tpltypename'=>'185_index_gjerf',
			'tpldesinfo'=>'图片高度75，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu brown',
			'sort'=>85,
		),
		array(
			'tpltypeid'=>86,
			'tplview'=>'cate186.png',
			'tpltypename'=>'186_index_aasd',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>86,
		),
		array(
			'tpltypeid'=>87,
			'tplview'=>'cate187.png',
			'tpltypename'=>'187_index_4d8fw',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>87,
		),
		array(
			'tpltypeid'=>88,
			'tplview'=>'cate188.png',
			'tpltypename'=>'188_index_gcbr5',
			'tpldesinfo'=>'图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu black',
			'sort'=>88,
		),
		array(
			'tpltypeid'=>89,
			'tplview'=>'cate189.png',
			'tpltypename'=>'189_index_xcv2',
			'tpldesinfo'=>'图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu black',
			'sort'=>89,
		),
		array(
			'tpltypeid'=>90,
			'tplview'=>'cate190.png',
			'tpltypename'=>'190_index_xj643',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'bgs thumb focu green2 blue',
			'sort'=>90,
		),
		array(
			'tpltypeid'=>91,
			'tplview'=>'cate191.png',
			'tpltypename'=>'191_index_zedv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu blue',
			'sort'=>91,
		),
		array(
			'tpltypeid'=>92,
			'tplview'=>'cate192.png',
			'tpltypename'=>'192_index_vbrn',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>92,
		),
		array(
			'tpltypeid'=>93,
			'tplview'=>'cate193.png',
			'tpltypename'=>'193_index_b4bt',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu orange pink',
			'sort'=>93,
		),
		array(
			'tpltypeid'=>94,
			'tplview'=>'cate194.png',
			'tpltypename'=>'194_index_sc23',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu pink',
			'sort'=>94,
		),
		array(
			'tpltypeid'=>95,
			'tplview'=>'cate195.png',
			'tpltypename'=>'195_index_xrb54',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu pink',
			'sort'=>95,
		),
		array(
			'tpltypeid'=>96,
			'tplview'=>'cate196.png',
			'tpltypename'=>'196_index_sdf3',
			'tpldesinfo'=>'图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>96,
		),
		array(
			'tpltypeid'=>97,
			'tplview'=>'cate197.png',
			'tpltypename'=>'197_index_cvrj',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu white',
			'sort'=>97,
		),
		array(
			'tpltypeid'=>98,
			'tplview'=>'cate198.png',
			'tpltypename'=>'198_index_xcwh',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu white',
			'sort'=>98,
		),
		array(
			'tpltypeid'=>99,
			'tplview'=>'cate199.png',
			'tpltypename'=>'199_index_asdw',
			'tpldesinfo'=>'图标为正方形300x300px，图片高度90，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu color purple',
			'sort'=>99,
		),
		array(
			'tpltypeid'=>100,
			'tplview'=>'cate1100.png',
			'tpltypename'=>'1100_index_btj5',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu bg filt slip green2',
			'sort'=>100,
		),
		array(
			'tpltypeid'=>101,
			'tplview'=>'cate1101.png',
			'tpltypename'=>'1101_index_sd3h',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu bg filt slip green2 blue',
			'sort'=>101,
		),
		array(
			'tpltypeid'=>102,
			'tplview'=>'cate1102.png',
			'tpltypename'=>'1102_index_cvb5u',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu bg filt slip green2 blue',
			'sort'=>102,
		),
		array(
			'tpltypeid'=>103,
			'tplview'=>'cate1103.png',
			'tpltypename'=>'index13816',
			'tpldesinfo'=>'分类的图片统一相同尺寸300x300正方形图片，不用做成圆形图片，系统自己会显示为圆形图片。',
			'attr'=>'bgs thumb focu blue',
			'sort'=>103,
		),
		array(
			'tpltypeid'=>104,
			'tplview'=>'cate1104.png',
			'tpltypename'=>'index13817',
			'tpldesinfo'=>'分类的图片统一相同尺寸300x300正方形图片，不用做成圆角图片，系统自己会显示为圆角图片。暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu green2',
			'sort'=>104,
		),
		array(
			'tpltypeid'=>105,
			'tplview'=>'cate1105.png',
			'tpltypename'=>'index13818',
			'tpldesinfo'=>'分类的图片统一相同尺寸300x300正方形图片，分类建议为3的倍数，否则影响展示效果。',
			'attr'=>'bgs thumb focu color green2',
			'sort'=>105,
		),
		array(
			'tpltypeid'=>106,
			'tplview'=>'cate1106.png',
			'tpltypename'=>'index13819',
			'tpldesinfo'=>'头部为首页封面图片外链720x400，高度可以根据自己情况调整，图标要统一尺寸，最好是150x150px的正方形透明png图片外链，也可以是统一的大小的圆形图等。暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu red2',
			'sort'=>106,
		),
		array(
			'tpltypeid'=>107,
			'tplview'=>'cate1107.png',
			'tpltypename'=>'index13820',
			'tpldesinfo'=>'分类的图片为300x300正方形图片，记住一定要相同的尺寸，都是300x300。暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu',
			'sort'=>107,
		),
		array(
			'tpltypeid'=>108,
			'tplview'=>'cate1108.png',
			'tpltypename'=>'index13822',
			'tpldesinfo'=>'分类的图片统一相同尺寸300x300正方形图片，不用做成圆形图片，系统自己会显示为圆形图片。暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu white',
			'sort'=>108,
		),
		array(
			'tpltypeid'=>109,
			'tplview'=>'cate1109.png',
			'tpltypename'=>'index13823',
			'tpldesinfo'=>'分类的图片建议为300x300正方形图片，保持一致尺寸。暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu blue white',
			'sort'=>109,
		),
		array(
			'tpltypeid'=>110,
			'tplview'=>'cate1110.png',
			'tpltypename'=>'index13824',
			'tpldesinfo'=>'分类的图片统一相同尺寸300x300正方形图片，不用做成圆角图片，系统自己会显示为圆角图片。',
			'attr'=>'bgs thumb focu blue white',
			'sort'=>110,
		),
		array(
			'tpltypeid'=>111,
			'tplview'=>'cate1111.png',
			'tpltypename'=>'index13827',
			'tpldesinfo'=>'分类的图片统一相同尺寸300x300正方形图片，暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu blue',
			'sort'=>111,
		),
		array(
			'tpltypeid'=>112,
			'tplview'=>'cate1112.png',
			'tpltypename'=>'index13828',
			'tpldesinfo'=>'图片建议尺寸为宽640*高320或近似等比例的图片。',
			'attr'=>'bgs thumb focu blue',
			'sort'=>112,
		),
		array(
			'tpltypeid'=>113,
			'tplview'=>'cate1113.png',
			'tpltypename'=>'index13830',
			'tpldesinfo'=>'图片建议尺寸为宽640*高320或近似等比例的图片。',
			'attr'=>'bgs thumb focu blue white',
			'sort'=>113,
		),
		array(
			'tpltypeid'=>114,
			'tplview'=>'cate1114.png',
			'tpltypename'=>'index13831',
			'tpldesinfo'=>'分类的图片统一相同尺寸300x300正方形图片，不用做成圆形图片，系统自己会显示为圆形图片。',
			'attr'=>'bgs thumb focu blue white',
			'sort'=>114,
		),
		array(
			'tpltypeid'=>115,
			'tplview'=>'cate1115.png',
			'tpltypename'=>'index13832',
			'tpldesinfo'=>'分类的图片可以是720x400，或者同比例缩小尺寸320x178，或者300x300正方形图片.但记住一定要相同的尺寸，要么都是320x178，要么都是300x300，不要不一样的尺寸，那样会造成模板图片不对齐，很难看。',
			'attr'=>'bgs thumb focu blue white',
			'sort'=>115,
		),
		array(
			'tpltypeid'=>116,
			'tplview'=>'cate1116.png',
			'tpltypename'=>'index13833',
			'tpldesinfo'=>'头部为首页封面图片外链720x400，高度可以根据自己情况调整，图标要统一尺寸，最好是150x150px的正方形透明png图片外链，也可以是统一的大小的圆形图等。',
			'attr'=>'bgs thumb focu blue white',
			'sort'=>116,
		),
		array(
			'tpltypeid'=>117,
			'tplview'=>'cate1117.png',
			'tpltypename'=>'index13835',
			'tpldesinfo'=>'头部为首页封面图片外链720x400，高度可以根据自己情况调整，图标要统一尺寸，最好是150x150px的正方形透明png图片外链，也可以是统一的大小的圆形图等。',
			'attr'=>'bgs thumb focu',
			'sort'=>117,
		),
		array(
			'tpltypeid'=>118,
			'tplview'=>'cate1118.png',
			'tpltypename'=>'index13836',
			'tpldesinfo'=>'图片建议尺寸为宽640*高320或近似等比例的图片，暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu blue purple',
			'sort'=>118,
		),
		array(
			'tpltypeid'=>119,
			'tplview'=>'cate1119.png',
			'tpltypename'=>'index13837',
			'tpldesinfo'=>'背景幻灯片尺寸为640x1136px，小图标300x300px。',
			'attr'=>'bgs thumb focu',
			'sort'=>119,
		),
		array(
			'tpltypeid'=>120,
			'tplview'=>'cate1120.png',
			'tpltypename'=>'index13838',
			'tpldesinfo'=>'头部中间菜单建议3的倍数。暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu green2 filt',
			'sort'=>120,
		),
		array(
			'tpltypeid'=>121,
			'tplview'=>'cate1121.png',
			'tpltypename'=>'index13839',
			'tpldesinfo'=>'背景幻灯片尺寸为640x1136px，小图标300x300px。',
			'attr'=>'bgs thumb focu',
			'sort'=>121,
		),
		array(
			'tpltypeid'=>122,
			'tplview'=>'cate1122.png',
			'tpltypename'=>'index13841',
			'tpldesinfo'=>'头部幻灯片建议尺寸720x400，高度可以根据自己情况调整，图标要统一尺寸，最好是150x150px的正方形透明png图片外链，也可以是统一的大小的圆形图等。',
			'attr'=>'bgs thumb focu pink white',
			'sort'=>122,
		),
		array(
			'tpltypeid'=>123,
			'tplview'=>'cate1123.png',
			'tpltypename'=>'index13843',
			'tpldesinfo'=>'头部幻灯片建议尺寸720x400，分类图标建议为统一大小PNG。',
			'attr'=>'bgs thumb focu black',
			'sort'=>123,
		),
		array(
			'tpltypeid'=>124,
			'tplview'=>'cate1124.png',
			'tpltypename'=>'index13844',
			'tpldesinfo'=>'分类图片建议为PNG，7个以内效果最佳。暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu blue filt',
			'sort'=>124,
		),
		array(
			'tpltypeid'=>125,
			'tplview'=>'cate1125.png',
			'tpltypename'=>'index13847',
			'tpldesinfo'=>'6个分类效果最佳。',
			'attr'=>'bgs thumb focu white filt',
			'sort'=>125,
		),
		array(
			'tpltypeid'=>126,
			'tplview'=>'cate1126.png',
			'tpltypename'=>'index13848',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，前4个一级分类可以突出显示，小图标。',
			'attr'=>'bgs thumb focu sub white',
			'sort'=>126,
		),
		array(
			'tpltypeid'=>127,
			'tplview'=>'cate1127.png',
			'tpltypename'=>'index13853',
			'tpldesinfo'=>'分类6个效果最好，选择透明小图标。',
			'attr'=>'bgs thumb focu green2 orange',
			'sort'=>127,
		),
		array(
			'tpltypeid'=>128,
			'tplview'=>'cate1128.png',
			'tpltypename'=>'index13854',
			'tpldesinfo'=>'类似WP系统的操作主界面，栏目不超过8个。',
			'attr'=>'bgs thumb focu color blue',
			'sort'=>128,
		),
		array(
			'tpltypeid'=>129,
			'tplview'=>'cate1129.png',
			'tpltypename'=>'index13855',
			'tpldesinfo'=>'很简单清爽的界面， 小图标注意选择。',
			'attr'=>'bgs thumb focu red2 color',
			'sort'=>129,
		),
		array(
			'tpltypeid'=>130,
			'tplview'=>'cate1130.png',
			'tpltypename'=>'index13856',
			'tpldesinfo'=>'一定要选择透明格式的PNG图标，否则效果很难看。',
			'attr'=>'bgs thumb focu',
			'sort'=>130,
		),
		array(
			'tpltypeid'=>131,
			'tplview'=>'cate1131.png',
			'tpltypename'=>'index13857',
			'tpldesinfo'=>'适合做展示类的网站。',
			'attr'=>'bgs thumb focu black',
			'sort'=>130,
		),
		array(
			'tpltypeid'=>132,
			'tplview'=>'cate1132.png',
			'tpltypename'=>'index13858',
			'tpldesinfo'=>'适合做服务类型。小图标请选择。',
			'attr'=>'bgs thumb focu',
			'sort'=>132,
		),
		array(
			'tpltypeid'=>133,
			'tplview'=>'cate1133.png',
			'tpltypename'=>'index13859',
			'tpldesinfo'=>'暂不支持底部一键拨号和版权。',
			'attr'=>'bgs thumb focu color',
			'sort'=>133,
		),
		array(
			'tpltypeid'=>134,
			'tplview'=>'cate1134.png',
			'tpltypename'=>'index13861',
			'tpldesinfo'=>'此模板支持播放音乐，轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，小图标300x300px。',
			'attr'=>'bgs thumb focu red2 color filt',
			'sort'=>134,
		),
		array(
			'tpltypeid'=>135,
			'tplview'=>'cate1135.png',
			'tpltypename'=>'index13862',
			'tpldesinfo'=>'可以一排四个，图片200x200px就好。',
			'attr'=>'bgs thumb focu color',
			'sort'=>135,
		),
		array(
			'tpltypeid'=>136,
			'tplview'=>'cate1136.png',
			'tpltypename'=>'index13863',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示8个二级分类。',
			'attr'=>'bgs thumb focu sub white',
			'sort'=>136,
		),
		array(
			'tpltypeid'=>137,
			'tplview'=>'cate1137.png',
			'tpltypename'=>'index13864',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示6个二级分类。',
			'attr'=>'bgs thumb focu sub white',
			'sort'=>137,
		),
		array(
			'tpltypeid'=>138,
			'tplview'=>'cate1138.png',
			'tpltypename'=>'index13865',
			'tpldesinfo'=>'分类的图片可以是720x400，或者同比例缩小尺寸320x178，或者300x300正方形图片.但记住一定要相同的尺寸，要么都是320x178，要么都是300x300，不要不一样的尺寸，那样会造成模板图片不对齐，很难看。',
			'attr'=>'bgs thumb focu blue',
			'sort'=>138,
		),
		array(
			'tpltypeid'=>139,
			'tplview'=>'cate1139.png',
			'tpltypename'=>'index13866',
			'tpldesinfo'=>'此模板轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，小图标300x300px,首页分类显示最好8个，不能超过8个。',
			'attr'=>'bgs thumb focu green2',
			'sort'=>139,
		),
		array(
			'tpltypeid'=>140,
			'tplview'=>'cate1140.png',
			'tpltypename'=>'index13867',
			'tpldesinfo'=>'此模板轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，小图标300x300px,首页分类显示最好8个，不能超过8个。',
			'attr'=>'bgs thumb focu filt',
			'sort'=>140,
		),
		array(
			'tpltypeid'=>141,
			'tplview'=>'cate1141.png',
			'tpltypename'=>'index13876',
			'tpldesinfo'=>'个性化的图块自动生成，用户无需修改。每行3个分类，效果最佳。',
			'attr'=>'bgs thumb focu',
			'sort'=>141,
		),
		array(
			'tpltypeid'=>142,
			'tplview'=>'cate1142.png',
			'tpltypename'=>'index13877',
			'tpldesinfo'=>'个性化的图块自动生成，用户无需修改。每行3个分类，效果最佳。',
			'attr'=>'bgs thumb focu sub white',
			'sort'=>142,
		),
		array(
			'tpltypeid'=>143,
			'tplview'=>'cate1143.png',
			'tpltypename'=>'index13878asdasfjks',
			'tpldesinfo'=>'支持二级分类，支持底部导航，支持WIFI登录。',
			'attr'=>'bgs thumb focu sub white slip',
			'sort'=>143,
		),
		array(
			'tpltypeid'=>144,
			'tplview'=>'cate1144.png',
			'tpltypename'=>'index13879dasdjuufd',
			'tpldesinfo'=>'支持二级分类，支持底部导航，支持WIFI登录。',
			'attr'=>'bgs thumb focu sub white slip',
			'sort'=>144,
		),
		array(
			'tpltypeid'=>145,
			'tplview'=>'cate1145.png',
			'tpltypename'=>'index13880jdhuhusjd',
			'tpldesinfo'=>'支持二级分类，支持底部导航，支持WIFI登录。',
			'attr'=>'bgs thumb focu sub white',
			'sort'=>145,
		),
		array(
			'tpltypeid'=>146,
			'tplview'=>'cate1146.png',
			'tpltypename'=>'index13881shfusdiff',
			'tpldesinfo'=>'支持二级分类，支持底部导航，支持WIFI登录。',
			'attr'=>'bgs thumb focu sub white slip',
			'sort'=>146,
		),
		array(
			'tpltypeid'=>147,
			'tplview'=>'cate1147.png',
			'tpltypename'=>'index13882dufhuhudf',
			'tpldesinfo'=>'支持二级分类，支持底部导航，支持WIFI登录。',
			'attr'=>'bgs thumb focu blue color',
			'sort'=>147,
		),
	
	);
	
	
return $tpl;

?>